//! Protocol-agnostic message envelopes that cross the MembraneGuest trait boundary.

use serde::{Deserialize, Serialize};

// ── Inbound (external → hotel) ────────────────────────────────────────────────

/// A message received from the external protocol, normalised for IPC dispatch.
///
/// The variant populates this from whatever protocol-specific event it received
/// (Telegram update, Discord interaction, MCP tools/call, etc.) and passes it
/// to the runtime via [`MembraneContext::inbound_tx`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboundEnvelope {
    /// Stable session identifier (e.g. Telegram chat_id, Discord channel_id,
    /// MCP session established at `initialize`).
    pub session_id: String,
    /// Per-turn identifier generated by the variant (UUID recommended).
    pub turn_id: String,
    /// Who sent this message.
    pub sender: SenderInfo,
    /// The primary text content of the message.
    pub content: String,
    /// Protocol-specific attachments (photos, voice, files, etc.).
    #[serde(default)]
    pub attachments: Vec<serde_json::Value>,
    /// Slash command name if this message was a command invocation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// Opaque reply-routing hint for the variant's `deliver()` implementation
    /// (e.g. Telegram thread_id, Discord channel_id, MCP correlation_id).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    /// Raw transport event — preserved for audit / debugging. Not forwarded to philote.
    pub raw_transport: serde_json::Value,
    /// When true, the receiving philote must park the turn as WaitingApproval
    /// before processing. Set by membrane variants that have per-route
    /// `require_approval` gates (e.g. membrane-mcp route security config).
    #[serde(default)]
    pub requires_approval: bool,
}

/// Identifies the sender of an inbound message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SenderInfo {
    /// Protocol-specific stable user ID.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Display name (first name, username, etc.).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Handle / username if available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// True if the hotel has classified this sender as an operator.
    #[serde(default)]
    pub is_operator: bool,
}

// ── Outbound (hotel → external) ───────────────────────────────────────────────

/// A reply delivered from the hotel to the variant for external transmission.
///
/// The runtime calls [`MembraneGuest::deliver`] with this value whenever the
/// hotel pushes a reply for an active session. The variant formats it for its
/// specific protocol (Telegram HTML, Discord embed, MCP tool result, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum OutboundReply {
    /// A complete text reply — send to the session/thread as-is.
    Text {
        session_id: String,
        turn_id: String,
        content: String,
        /// Routing hint echoed from the original [`InboundEnvelope::reply_to`].
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reply_to: Option<String>,
    },
    /// An incremental streaming token — accumulate and throttle-edit.
    StreamingToken {
        session_id: String,
        turn_id: String,
        token: String,
    },
    /// The turn ended with an error — surface to the user appropriately.
    Error {
        session_id: String,
        turn_id: String,
        message: String,
    },
    /// The philote is waiting for operator approval before proceeding.
    ApprovalRequired {
        session_id: String,
        turn_id: String,
        description: String,
        #[serde(default)]
        options: Vec<String>,
    },
}

impl OutboundReply {
    pub fn session_id(&self) -> &str {
        match self {
            Self::Text { session_id, .. }
            | Self::StreamingToken { session_id, .. }
            | Self::Error { session_id, .. }
            | Self::ApprovalRequired { session_id, .. } => session_id,
        }
    }

    pub fn turn_id(&self) -> &str {
        match self {
            Self::Text { turn_id, .. }
            | Self::StreamingToken { turn_id, .. }
            | Self::Error { turn_id, .. }
            | Self::ApprovalRequired { turn_id, .. } => turn_id,
        }
    }
}
