// V005: Life Graph OS — soft-zoning domain Role seed + per-agent provenance indexes
// Target:  Memgraph 3.10.1+
// Host:    vps-jane Tailscale 100.64.212.8:7687
// Depends: V001__life_graph_schema.cypher, V004__aspiration_civic_core.cypher
//
// One shared graph, soft boundaries. Seeds the 7 steward domain Role nodes so
// every agent has a stable anchor for OWNS/SHAPES/SETS/SPAWNS/RELATES_TO
// living-cycle edges, and indexes the new observed_by provenance property
// written by life.observe ("who observed this", distinct from source_membrane
// which records the transport).
//
// Reconciliation with the 8 pre-existing Role nodes (audited 2026-07-06):
//   human                        -> reused: Human domain (coach, health + workouts)
//   life:role:musician           -> reused: Musician domain (bjork)
//   life:role:ai_architect       -> reused: Architect domain (aria)
//   life:role:husband            -> untouched (operator's personal life role)
//   life:role:father             -> untouched
//   life:role:friend             -> untouched
//   life:role:brother_son        -> untouched
//   life:role:toastmasters-sergeant-at-arms -> untouched
//
// Statements are generated by data_memorygraphrag::zoning::compile_domain_role_seed_statements()
// and MERGE by id — the seed is idempotent, never deletes, and preserves any
// existing display name via coalesce.
//
// Apply each statement individually — Bolt does not support multi-statement batches.

// ============================================================
// Domain Role seed (MERGE-only, idempotent)
// ============================================================

MERGE (r:Role {id: "life:role:librarian"}) SET r.name = coalesce(r.name, "Librarian"), r.domain_slug = "librarian", r.steward_agent = "astrid", r.domain_scope = "notes + Obsidian", r.zoning_seed = "V005";

MERGE (r:Role {id: "life:role:communications"}) SET r.name = coalesce(r.name, "Communications"), r.domain_slug = "communications", r.steward_agent = "ariel", r.domain_scope = "contacts + relationships", r.zoning_seed = "V005";

MERGE (r:Role {id: "life:role:companion"}) SET r.name = coalesce(r.name, "Companion"), r.domain_slug = "companion", r.steward_agent = "jane", r.domain_scope = "companionship", r.zoning_seed = "V005";

MERGE (r:Role {id: "life:role:ai_architect"}) SET r.name = coalesce(r.name, "Architect"), r.domain_slug = "architect", r.steward_agent = "aria", r.domain_scope = "philotic + AI research", r.zoning_seed = "V005";

MERGE (r:Role {id: "life:role:chief-of-staff"}) SET r.name = coalesce(r.name, "ChiefOfStaff"), r.domain_slug = "chief_of_staff", r.steward_agent = "beacon", r.domain_scope = "goals + open loops + progress", r.zoning_seed = "V005";

MERGE (r:Role {id: "life:role:musician"}) SET r.name = coalesce(r.name, "Musician"), r.domain_slug = "musician", r.steward_agent = "bjork", r.domain_scope = "music", r.zoning_seed = "V005";

MERGE (r:Role {id: "human"}) SET r.name = coalesce(r.name, "Human"), r.domain_slug = "human", r.steward_agent = "coach", r.domain_scope = "health + workouts", r.zoning_seed = "V005";

// ============================================================
// Property Indexes — per-agent provenance ("who observed this")
// ============================================================

CREATE INDEX ON :Role(domain_slug);
CREATE INDEX ON :Signal(observed_by);
CREATE INDEX ON :OpenLoop(observed_by);
CREATE INDEX ON :Goal(observed_by);
CREATE INDEX ON :Event(observed_by);
CREATE INDEX ON :Aspiration(observed_by);
